'use client';
import { useEffect, useMemo, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowPathIcon, CheckCircleIcon, ClockIcon, HeartIcon, MagnifyingGlassIcon, MapPinIcon, PlusIcon, XMarkIcon } from '@heroicons/react/24/outline';
import type { Attraction, Booking, CountryName, DayPeriod, HotelStay, ItineraryItem } from '@/lib/db';
import { put } from '@/lib/db';

const countries: CountryName[]=['Malaysia','Singapore','Indonesia'];
const dates:Record<CountryName,string[]>={Malaysia:['2026-08-22','2026-08-23','2026-08-24','2026-08-25'],Singapore:['2026-08-26','2026-08-27','2026-08-28','2026-08-29'],Indonesia:['2026-08-30','2026-08-31','2026-09-01','2026-09-02']};
const time:Record<DayPeriod,string>={Morning:'09:00',Afternoon:'14:00',Evening:'18:30'};
const money=(value?:number)=>Number.isFinite(value)?Number(value).toLocaleString():'—';
const checked=(value?:string)=>value?new Date(`${value}T00:00`).toLocaleDateString('en-AE',{day:'numeric',month:'short',year:'numeric'}):'Not available';

type RouteEstimate={distanceKm:number;drivingMinutes:number;walking:{minutes:number;practical:boolean;note:string};transit:{mode:string;minutes:number;cost:number;currency:string;note:string};error?:string};
const shouldShowWalking = (route?: RouteEstimate) => !route || !(route.walking.minutes > 30 || route.distanceKm > 10);
const guides:Record<CountryName,{title:string;card:string;cardCost:string;trip:string;tip:string}>={
 Malaysia:{title:'Cheapest: Rapid KL rail and bus',card:'Touch ’n Go card',cardCost:'Card purchase price varies by outlet; load travel credit separately.',trip:'Typical Rapid KL rail trips: about MYR 1.20–9.50.',tip:'Use MRT/LRT/Monorail in Kuala Lumpur. For Genting, take a coach to Awana and continue by cable car.'},
 Singapore:{title:'Cheapest: MRT and public bus',card:'Contactless bank card or SimplyGo/EZ-Link',cardCost:'A separate tourist card is optional; a contactless Visa/Mastercard can be used directly.',trip:'Adult public-transport fare is distance based, roughly SGD 1.28–2.57.',tip:'Tap in and out with the same card. MRT is usually fastest; buses are useful for the last kilometre.'},
 Indonesia:{title:'Cheapest: TransJakarta, MRT and Mikrotrans',card:'JakLingko-compatible e-money card',cardCost:'Card purchase price depends on issuer and outlet; top-up is separate.',trip:'TransJakarta is commonly IDR 3,500; MRT Jakarta is distance based, about IDR 3,000–14,000.',tip:'Use MRT/TransJakarta for the main route and Gojek/Grab only for the short last mile.'},
};

export default function CountryExplorer({attractions,hotels,bookings,initialCountry='Malaysia',onRefresh,onOpenItinerary}:{attractions:Attraction[];hotels:HotelStay[];bookings:Booking[];initialCountry?:CountryName;onRefresh:()=>Promise<void>|void;onOpenItinerary:()=>void}){
 const [country,setCountry]=useState<CountryName>(initialCountry); const [query,setQuery]=useState(''); const [category,setCategory]=useState('All'); const [selected,setSelected]=useState<Attraction|null>(null); const [planning,setPlanning]=useState<Attraction|null>(null); const [routes,setRoutes]=useState<Record<string,RouteEstimate>>({}); const [loading,setLoading]=useState<Record<string,boolean>>({});
 useEffect(()=>setCountry(initialCountry),[initialCountry]);
 const savedHotel=hotels.find(h=>h.country===country);
 const hotelBooking=bookings.find(b=>b.country===country&&b.type==='hotel');
 const hotel=savedHotel&&savedHotel.address!=='Add hotel address'&&!savedHotel.name.startsWith('Add ')?savedHotel:hotelBooking?{name:hotelBooking.title,address:hotelBooking.subtitle,city:country,country}:savedHotel;
 const hasHotel=Boolean(hotel&&hotel.address&&hotel.address!=='Add hotel address'&&hotel.name&&!hotel.name.startsWith('Add '));
 const list=useMemo(()=>attractions.filter(a=>Boolean(a.description)).filter(a=>a.country===country).filter(a=>`${a.name} ${a.city} ${a.category} ${a.description||''}`.toLowerCase().includes(query.toLowerCase())).filter(a=>category==='All'||a.category===category),[attractions,country,query,category]);
 const categories=['All',...Array.from(new Set(attractions.filter(a=>Boolean(a.description)&&a.country===country).map(a=>a.category)))];
 useEffect(()=>{
  if(!hasHotel||!hotel) return;
  const destinations=list.filter(a=>Number.isFinite(a.latitude)&&Number.isFinite(a.longitude)&&!routes[a.id]).map(a=>({id:a.id,lat:Number(a.latitude),lon:Number(a.longitude),country:a.country}));
  if(!destinations.length) return;
  const controller=new AbortController();
  setLoading(v=>({...v,...Object.fromEntries(destinations.map(d=>[d.id,true]))}));
  fetch('/api/travel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({origin:`${hotel.name}, ${hotel.address}, ${hotel.city}, ${hotel.country}`,destinations}),signal:controller.signal})
   .then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to calculate routes.');setRoutes(v=>({...v,...data.routes}));})
   .catch(error=>{if(error?.name!=='AbortError')setRoutes(v=>({...v,...Object.fromEntries(destinations.map(d=>[d.id,{distanceKm:0,drivingMinutes:0,walking:{minutes:0,practical:false,note:'Unavailable'},transit:{mode:'Unavailable',minutes:0,cost:0,currency:'',note:error instanceof Error?error.message:'Unable to calculate.'},error:error instanceof Error?error.message:'Unable to calculate.'}]))}));})
   .finally(()=>setLoading(v=>({...v,...Object.fromEntries(destinations.map(d=>[d.id,false]))})));
  return()=>controller.abort();
 },[country,hasHotel,hotel?.name,hotel?.address,hotel?.city,list.length]);
 async function toggle(a:Attraction,key:'wishlist'|'visited'|'saved'){await put('attractions',{...a,[key]:!a[key]}); await onRefresh(); setSelected(s=>s?.id===a.id?{...a,[key]:!a[key]}:s)}
 async function add(a:Attraction,date:string,period:DayPeriod){const item:ItineraryItem={id:crypto.randomUUID(),title:a.name,location:`${a.address||''}${a.city?`, ${a.city}`:''}`,date,time:time[period],country:a.country,period,notes:[a.duration,a.bestTime].filter(Boolean).join(' · '),attractionId:a.id};await put('itinerary',item);await onRefresh();setPlanning(null);onOpenItinerary()}
 async function calculate(a:Attraction){if(!hasHotel||!hotel||!Number.isFinite(a.latitude)||!Number.isFinite(a.longitude))return;setLoading(v=>({...v,[a.id]:true}));try{const q=new URLSearchParams({hotel:`${hotel.name}, ${hotel.address}, ${hotel.city}, ${hotel.country}`,lat:String(a.latitude),lon:String(a.longitude),country:a.country});const r=await fetch(`/api/travel?${q}`);const data=await r.json();setRoutes(v=>({...v,[a.id]:r.ok?data:{distanceKm:0,drivingMinutes:0,walking:{minutes:0,practical:false,note:'Unavailable'},transit:{mode:'Unavailable',minutes:0,cost:0,currency:a.currency||'',note:data.error||'Unable to calculate.'},error:data.error}}))}finally{setLoading(v=>({...v,[a.id]:false}))}}
 return <section className="explorer-shell">
  <div className="section-heading"><div><span className="eyebrow">COUNTRY EXPLORER</span><h3>Plan the best stops</h3></div><span className="muted">{list.length} places</span></div>
  <div className="explorer-country-tabs">{countries.map(c=><button key={c} className={country===c?'active':''} onClick={()=>{setCountry(c);setCategory('All')}}><b>{c.slice(0,2).toUpperCase()}</b><span>{c}</span></button>)}</div>
  <section className="commute-guide glass"><div><span className="eyebrow">GETTING AROUND</span><h4>{guides[country].title}</h4><p>{guides[country].tip}</p></div><div className="commute-facts"><span><b>{guides[country].card}</b>{guides[country].cardCost}</span><span><b>Typical trip cost</b>{guides[country].trip}</span></div></section>
  <div className={`hotel-route-banner ${hasHotel?'ready':'missing'}`}><MapPinIcon/><div><b>{hasHotel?`Routes from ${hotel?.name}`:'Add your hotel address to calculate routes'}</b><span>{hasHotel?hotel?.address:'Open Stays, edit the hotel for this country, and enter a complete street address.'}</span></div></div>
  <div className="explorer-filters glass"><label><MagnifyingGlassIcon/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search attractions or cities"/></label><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
  <div className="explorer-grid">{list.map((a,i)=>{const route=routes[a.id];return <motion.article className="explorer-card" key={a.id} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{delay:Math.min(i*.025,.2)}}>
   <div className="explorer-card-head"><span>{a.category}</span><div><button className={a.wishlist?'on':''} onClick={()=>toggle(a,'wishlist')} aria-label="Wishlist"><HeartIcon/></button><button className={a.visited?'on':''} onClick={()=>toggle(a,'visited')} aria-label="Visited"><CheckCircleIcon/></button></div></div>
   <div className="explorer-pin"><MapPinIcon/></div><h4>{a.name}</h4><p>{a.description||`${a.category} attraction in ${a.city}.`}</p>
   <div className="explorer-tags"><span>{a.city}</span><span>{a.indoor&&a.outdoor?'Indoor + outdoor':a.indoor?'Indoor':'Outdoor'}</span>{a.familyFriendly&&<span>Family friendly</span>} {a.duration&&<span>{a.duration}</span>}</div>
   <div className="explorer-price"><div><small>Adult</small><b>{a.freeEntry?'Free':`${a.currency||''} ${money(a.adultPrice)}`}</b><em>{a.freeEntry?'No ticket':Number.isFinite(a.aedAdult)?`≈ AED ${money(a.aedAdult)}`:'Price unavailable'}</em></div><div><small>Child</small><b>{a.freeEntry?'Free':Number.isFinite(a.childPrice)?`${a.currency||''} ${money(a.childPrice)}`:'Check venue'}</b><em>{Number.isFinite(a.aedChild)?`≈ AED ${money(a.aedChild)}`:' '}</em></div></div>
   <div className="route-estimate">{route?.error?<span className="route-error">{route.error}</span>:route?<><div><b>{route.distanceKm} km</b><span>from hotel</span></div><div><b>~{route.transit.minutes} min</b><span>{route.transit.mode}</span></div><div><b>~{route.transit.currency} {money(route.transit.cost)}</b><span>estimated fare</span></div>{shouldShowWalking(route)&&<div><b>~{route.walking.minutes} min</b><span>walk</span></div>}</>:<button disabled={!hasHotel||loading[a.id]} onClick={()=>calculate(a)}>{loading[a.id]?<ArrowPathIcon className="spin"/>:<MapPinIcon/>}{hasHotel?'Calculate from hotel':'Add hotel address first'}</button>}</div>
   <small className="explorer-checked">Last checked {checked(a.lastChecked)} · Travel times and fares are estimates.</small><div className="explorer-actions"><button onClick={()=>setSelected(a)}>Details</button><button className="primary small" onClick={()=>setPlanning(a)}><PlusIcon/> Add</button></div>
  </motion.article>})}</div>
  {!list.length&&<div className="empty"><MagnifyingGlassIcon/><h4>No matching attractions</h4><p>Try another country, category, or search.</p></div>}
  <AnimatePresence>{selected&&<motion.div className="sheet-backdrop" onClick={()=>setSelected(null)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.aside className="detail-sheet" onClick={e=>e.stopPropagation()} initial={{y:'100%'}} animate={{y:0}} exit={{y:'100%'}} transition={{type:'spring',damping:28,stiffness:280}}><button className="sheet-close" onClick={()=>setSelected(null)}><XMarkIcon/></button><span className="eyebrow">{selected.country} · {selected.category}</span><h3>{selected.name}</h3><p>{selected.description}</p><div className="detail-list"><div><b>Best time</b><span>{selected.bestTime||'Check venue'}</span></div><div><b>Duration</b><span>{selected.duration||'Flexible'}</span></div><div><b>Accessibility</b><span>{selected.accessibility||'Contact venue'}</span></div><div><b>Pricing note</b><span>{selected.pricingNote||'Prices are approximate and may change.'}</span></div>{routes[selected.id]&&!routes[selected.id].error&&<div><b>Cheapest suggested route</b><span>{routes[selected.id].transit.note}</span></div>}</div><div className="nearby-links">{['food','shopping','ATM','mosque','hospital','transport'].map(x=><a key={x} target="_blank" rel="noreferrer" href={`https://www.google.com/maps/search/${encodeURIComponent(`${x} near ${selected.latitude},${selected.longitude}`)}`}>{x}</a>)}</div><div className="sheet-actions">{shouldShowWalking(routes[selected.id])&&<a className="secondary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${selected.latitude},${selected.longitude}${hasHotel?`&origin=${encodeURIComponent(`${hotel?.name}, ${hotel?.address}`)}`:''}&travelmode=walking`}>Walking directions</a>}<a className="secondary" target="_blank" rel="noreferrer" href={`https://www.google.com/maps/dir/?api=1&destination=${selected.latitude},${selected.longitude}${hasHotel?`&origin=${encodeURIComponent(`${hotel?.name}, ${hotel?.address}`)}`:''}&travelmode=transit`}>Transit directions</a><button className="primary" onClick={()=>setPlanning(selected)}>Add to itinerary</button></div></motion.aside></motion.div>}</AnimatePresence>
  <AnimatePresence>{planning&&<motion.div className="sheet-backdrop" onClick={()=>setPlanning(null)} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.aside className="plan-sheet" onClick={e=>e.stopPropagation()} initial={{scale:.96,opacity:0}} animate={{scale:1,opacity:1}} exit={{scale:.96,opacity:0}}><button className="sheet-close" onClick={()=>setPlanning(null)}><XMarkIcon/></button><span className="eyebrow">ADD TO DAY</span><h3>{planning.name}</h3>{dates[planning.country].map(d=><div className="plan-date" key={d}><b>{new Date(`${d}T00:00`).toLocaleDateString('en-AE',{weekday:'short',day:'numeric',month:'short'})}</b><div>{(['Morning','Afternoon','Evening'] as DayPeriod[]).map(p=><button key={p} onClick={()=>add(planning,d,p)}><ClockIcon/>{p}</button>)}</div></div>)}</motion.aside></motion.div>}</AnimatePresence>
 </section>
}
