import { NextRequest, NextResponse } from 'next/server';
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];
const countryFor=(lat:number,lon:number)=> lat>=1.15&&lat<=1.5&&lon>=103.55&&lon<=104.1?'Singapore':lat>=.8&&lat<=7.5&&lon>=99.5&&lon<=119.5?'Malaysia':lat>=-11.5&&lat<=6.5&&lon>=94.5&&lon<=141.5?'Indonesia':'';
function fare(country:string,km:number,minutes:number){if(country==='Singapore')return{min:Number((4.8+km*.85+minutes*.18).toFixed(2)),max:Number((7+km*1.25+minutes*.3).toFixed(2)),currency:'SGD'};if(country==='Indonesia')return{min:Math.round((10000+km*3500+minutes*350)/1000)*1000,max:Math.round((18000+km*6500+minutes*650)/1000)*1000,currency:'IDR'};return{min:Number((4+km*1.15+minutes*.18).toFixed(2)),max:Number((8+km*2+minutes*.35).toFixed(2)),currency:'MYR'};}
async function overpass(query:string){for(const endpoint of endpoints){try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'TripDeck/2.0 live-shops'},body:new URLSearchParams({data:query}),cache:'no-store',signal:AbortSignal.timeout(22000)});if(r.ok)return await r.json();}catch{}}throw new Error('shop provider');}
async function route(lat:number,lon:number,dlat:number,dlon:number){try{const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${lon},${lat};${dlon},${dlat}?overview=false`,{cache:'no-store',signal:AbortSignal.timeout(12000)});const d=await r.json();return d.routes?.[0]||null;}catch{return null;}}
export async function GET(request:NextRequest){const lat=Number(request.nextUrl.searchParams.get('lat')),lon=Number(request.nextUrl.searchParams.get('lon')),radius=Math.min(10000,Math.max(1000,Number(request.nextUrl.searchParams.get('radius'))||5000));if(!Number.isFinite(lat)||!Number.isFinite(lon))return NextResponse.json({error:'Location coordinates are required.'},{status:400});const country=countryFor(lat,lon);if(!country)return NextResponse.json({error:'Live shop search is limited to Malaysia, Singapore and Indonesia.'},{status:400});const query=`[out:json][timeout:20];nwr(around:${radius},${lat},${lon})[shop][name];out center tags 30;`;try{const data=await overpass(query);const base=(data.elements||[]).map((e:any)=>{const p=e.center||e,t=e.tags||{};return Number.isFinite(p.lat)&&Number.isFinite(p.lon)?{id:`${e.type}${e.id}`,name:t.name,category:t.shop||'shop',lat:p.lat,lon:p.lon,address:[t['addr:housenumber'],t['addr:street'],t['addr:city']].filter(Boolean).join(' ')||'Open map for address',openingHours:t.opening_hours||'',website:t.website||t['contact:website']||''}:null}).filter(Boolean).slice(0,12);const shops=await Promise.all(base.map(async(s:any)=>{const r=await route(lat,lon,s.lat,s.lon);if(!r)return{...s,routeUnavailable:true};const distanceKm=Number((r.distance/1000).toFixed(1)),driveMinutes=Math.max(1,Math.round(r.duration/60));return{...s,distanceKm,driveMinutes,fare:fare(country,distanceKm,driveMinutes)};}));return NextResponse.json({country,shops,checkedAt:new Date().toISOString(),notice:'Shops, road distance and driving time are fetched live. Fare is a route-based estimate; open the ride-hailing app for the current quoted fare.'},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'Live shops are temporarily unavailable.'},{status:503});}}
