import type { Attraction } from './db';
const checked='2026-07-24';
const a=(x:Attraction)=>x;
export const attractionDataset: Attraction[] = [
// Malaysia — Kuala Lumpur, Genting Highlands and island day trips
 a({id:'my-petronas',country:'Malaysia',city:'Kuala Lumpur',name:'Petronas Twin Towers',category:'Landmark',description:'Skybridge and observation deck with panoramic city views.',adultPrice:98,childPrice:50,currency:'MYR',aedAdult:83,aedChild:42,lastChecked:checked,pricingNote:'Online time-slot price estimate; availability varies.',latitude:3.1579,longitude:101.7117,indoor:true,outdoor:false,familyFriendly:true,duration:'1.5–2 hours',bestTime:'Late afternoon',accessibility:'Wheelchair accessible lifts and facilities',address:'Petronas Twin Towers, Kuala Lumpur City Centre',saved:false}),
 a({id:'my-batu',country:'Malaysia',city:'Kuala Lumpur',name:'Batu Caves',category:'Culture',description:'Limestone caves, Hindu shrines and the iconic rainbow staircase.',adultPrice:0,childPrice:0,currency:'MYR',aedAdult:0,aedChild:0,freeEntry:true,lastChecked:checked,pricingNote:'Main temple complex is free; some caves charge separately.',latitude:3.2379,longitude:101.684,indoor:false,outdoor:true,familyFriendly:true,duration:'2–3 hours',bestTime:'Early morning',accessibility:'Many steep steps; limited wheelchair access',address:'Batu Caves, Gombak, Selangor',saved:false}),
 a({id:'my-aquaria',country:'Malaysia',city:'Kuala Lumpur',name:'Aquaria KLCC',category:'Family',description:'Large indoor aquarium beneath Kuala Lumpur Convention Centre.',adultPrice:75,childPrice:65,currency:'MYR',aedAdult:63,aedChild:55,lastChecked:checked,pricingNote:'Non-Malaysian visitor estimate; promotions vary.',latitude:3.1535,longitude:101.7131,indoor:true,outdoor:false,familyFriendly:true,duration:'2 hours',bestTime:'Midday or rainy day',accessibility:'Wheelchair and stroller friendly',address:'Kuala Lumpur Convention Centre, KLCC',saved:false}),
 a({id:'my-klbird',country:'Malaysia',city:'Kuala Lumpur',name:'KL Bird Park',category:'Nature',description:'Walk-through free-flight aviary in the Lake Gardens.',adultPrice:85,childPrice:60,currency:'MYR',aedAdult:72,aedChild:51,lastChecked:checked,pricingNote:'Foreign visitor admission estimate.',latitude:3.1422,longitude:101.688,indoor:false,outdoor:true,familyFriendly:true,duration:'2–3 hours',bestTime:'Morning',accessibility:'Mostly paved; some slopes',address:'920 Jalan Cenderawasih, Kuala Lumpur',saved:false}),
 a({id:'my-islamic',country:'Malaysia',city:'Kuala Lumpur',name:'Islamic Arts Museum Malaysia',category:'Museum',description:'Decorative arts, manuscripts and architecture from across the Islamic world.',adultPrice:20,childPrice:10,currency:'MYR',aedAdult:17,aedChild:8,lastChecked:checked,pricingNote:'Children under six may enter free.',latitude:3.1413,longitude:101.6896,indoor:true,outdoor:false,familyFriendly:true,duration:'2 hours',bestTime:'Afternoon',accessibility:'Wheelchair accessible',address:'Jalan Lembah Perdana, Kuala Lumpur',saved:false}),
 a({id:'my-sunway',country:'Malaysia',city:'Subang Jaya',name:'Sunway Lagoon',category:'Theme park',description:'Water rides, wildlife, amusement zones and family attractions.',adultPrice:250,childPrice:210,currency:'MYR',aedAdult:211,aedChild:177,lastChecked:checked,pricingNote:'Indicative online foreign visitor price; packages vary.',latitude:3.0713,longitude:101.6067,indoor:false,outdoor:true,familyFriendly:true,duration:'Full day',bestTime:'Weekday opening time',accessibility:'Accessible routes available; ride restrictions apply',address:'3 Jalan PJS 11/11, Bandar Sunway',saved:false}),
 a({id:'my-genting-skyworlds',country:'Malaysia',city:'Genting Highlands',name:'Genting SkyWorlds Theme Park',category:'Theme park',description:'High-altitude movie-themed park with rides and family zones.',adultPrice:168,childPrice:128,currency:'MYR',aedAdult:142,aedChild:108,lastChecked:checked,pricingNote:'Dated online ticket estimate; peak-day prices vary.',latitude:3.4236,longitude:101.7932,indoor:false,outdoor:true,familyFriendly:true,duration:'Full day',bestTime:'Opening time',accessibility:'Accessible paths; ride transfer requirements vary',address:'Genting SkyWorlds, Genting Highlands, Pahang',saved:false}),
 a({id:'my-awana-skyway',country:'Malaysia',city:'Genting Highlands',name:'Awana SkyWay',category:'Views',description:'Cable-car ride through the rainforest to Resorts World Genting.',adultPrice:20,childPrice:20,currency:'MYR',aedAdult:17,aedChild:17,lastChecked:checked,pricingNote:'Standard return fare estimate; express lane costs more.',latitude:3.4009,longitude:101.7816,indoor:true,outdoor:true,familyFriendly:true,duration:'45–90 minutes',bestTime:'Morning or before sunset',accessibility:'Wheelchair access available with staff assistance',address:'Awana SkyCentral, Genting Highlands',saved:false}),
 a({id:'my-chin-swee',country:'Malaysia',city:'Genting Highlands',name:'Chin Swee Caves Temple',category:'Culture',description:'Hilltop temple with pagoda, statues and sweeping mountain views.',adultPrice:0,childPrice:0,currency:'MYR',aedAdult:0,aedChild:0,freeEntry:true,lastChecked:checked,pricingNote:'Free entry; donations optional.',latitude:3.4145,longitude:101.7852,indoor:true,outdoor:true,familyFriendly:true,duration:'1–2 hours',bestTime:'Morning',accessibility:'Lifts available, with some sloped outdoor areas',address:'Chin Swee Caves Temple, Genting Highlands',saved:false}),
 a({id:'my-skytropolis',country:'Malaysia',city:'Genting Highlands',name:'Skytropolis Indoor Theme Park',category:'Family',description:'Indoor rides and games inside Resorts World Genting.',adultPrice:75,childPrice:75,currency:'MYR',aedAdult:63,aedChild:63,lastChecked:checked,pricingNote:'Unlimited ride pass estimate; individual ride credits also available.',latitude:3.4247,longitude:101.7935,indoor:true,outdoor:false,familyFriendly:true,duration:'3–4 hours',bestTime:'Afternoon or rainy day',accessibility:'Accessible common areas; ride rules vary',address:'First World Plaza, Genting Highlands',saved:false}),
 a({id:'my-langkwai-skybridge',country:'Malaysia',city:'Langkawi',name:'Langkawi SkyCab & SkyBridge',category:'Island',description:'Mountain cable car and curved pedestrian bridge above Langkawi rainforest.',adultPrice:85,childPrice:65,currency:'MYR',aedAdult:72,aedChild:55,lastChecked:checked,pricingNote:'Standard combo estimate; premium cabins and attractions extra.',latitude:6.3711,longitude:99.6712,indoor:true,outdoor:true,familyFriendly:true,duration:'3–4 hours',bestTime:'Clear morning',accessibility:'Cable car accessible; bridge includes stairs or paid lift',address:'Oriental Village, Burau Bay, Langkawi',saved:false}),
 a({id:'my-pangkor',country:'Malaysia',city:'Pangkor Island',name:'Pangkor Island Day Trip',category:'Island',description:'Beaches, fishing villages, Dutch Fort and coastal viewpoints.',adultPrice:40,childPrice:25,currency:'MYR',aedAdult:34,aedChild:21,lastChecked:checked,pricingNote:'Approximate return ferry only; local taxi and activities extra.',latitude:4.2275,longitude:100.5577,indoor:false,outdoor:true,familyFriendly:true,duration:'Full day',bestTime:'Early departure',accessibility:'Ferry and beach access vary',address:'Pangkor Island Ferry Terminal, Perak',saved:false}),

// Singapore
 a({id:'sg-gardens',country:'Singapore',city:'Singapore',name:'Gardens by the Bay',category:'Nature',description:'Supertrees, waterfront gardens and climate-controlled conservatories.',adultPrice:32,childPrice:18,currency:'SGD',aedAdult:92,aedChild:52,lastChecked:checked,pricingNote:'Outdoor gardens are free; conservatory bundle estimate shown.',latitude:1.2816,longitude:103.8636,indoor:true,outdoor:true,familyFriendly:true,duration:'3–4 hours',bestTime:'Late afternoon to evening',accessibility:'Wheelchair accessible; rentals available',address:'18 Marina Gardens Drive, Singapore',saved:false}),
 a({id:'sg-zoo',country:'Singapore',city:'Singapore',name:'Singapore Zoo',category:'Family',description:'Open-concept wildlife park with tropical habitats and shows.',adultPrice:49,childPrice:34,currency:'SGD',aedAdult:141,aedChild:98,lastChecked:checked,pricingNote:'Online admission estimate; dynamic discounts may apply.',latitude:1.4043,longitude:103.793,indoor:false,outdoor:true,familyFriendly:true,duration:'4–6 hours',bestTime:'Opening time',accessibility:'Wheelchair and stroller friendly',address:'80 Mandai Lake Road, Singapore',saved:false}),
 a({id:'sg-night-safari',country:'Singapore',city:'Singapore',name:'Night Safari',category:'Wildlife',description:'Nocturnal wildlife park with tram ride and walking trails.',adultPrice:58,childPrice:41,currency:'SGD',aedAdult:167,aedChild:118,lastChecked:checked,pricingNote:'Timed-entry online estimate.',latitude:1.4022,longitude:103.788,indoor:false,outdoor:true,familyFriendly:true,duration:'3–4 hours',bestTime:'First evening slot',accessibility:'Wheelchair accessible tram and paths',address:'80 Mandai Lake Road, Singapore',saved:false}),
 a({id:'sg-artscience',country:'Singapore',city:'Singapore',name:'ArtScience Museum',category:'Museum',description:'Interactive exhibitions at the lotus-shaped Marina Bay museum.',adultPrice:30,childPrice:25,currency:'SGD',aedAdult:86,aedChild:72,lastChecked:checked,pricingNote:'Future World standard ticket estimate; exhibitions priced separately.',latitude:1.2863,longitude:103.8593,indoor:true,outdoor:false,familyFriendly:true,duration:'2 hours',bestTime:'Midday',accessibility:'Fully wheelchair accessible',address:'6 Bayfront Avenue, Singapore',saved:false}),
 a({id:'sg-sentosa',country:'Singapore',city:'Singapore',name:'Singapore Cable Car',category:'Views',description:'Aerial ride linking Mount Faber, HarbourFront and Sentosa.',adultPrice:35,childPrice:25,currency:'SGD',aedAdult:101,aedChild:72,lastChecked:checked,pricingNote:'Round-trip Mount Faber Line estimate.',latitude:1.2711,longitude:103.8199,indoor:true,outdoor:false,familyFriendly:true,duration:'1–2 hours',bestTime:'Before sunset',accessibility:'Wheelchair access subject to station guidance',address:'109 Mount Faber Road, Singapore',saved:false}),
 a({id:'sg-botanic',country:'Singapore',city:'Singapore',name:'Singapore Botanic Gardens',category:'Nature',description:'UNESCO-listed tropical gardens with lakes and rainforest trails.',adultPrice:0,childPrice:0,currency:'SGD',aedAdult:0,aedChild:0,freeEntry:true,lastChecked:checked,pricingNote:'Main gardens are free; National Orchid Garden charges admission.',latitude:1.3138,longitude:103.8159,indoor:false,outdoor:true,familyFriendly:true,duration:'2–4 hours',bestTime:'Early morning',accessibility:'Accessible main paths; some natural slopes',address:'1 Cluny Road, Singapore',saved:false}),
 a({id:'sg-universal',country:'Singapore',city:'Singapore',name:'Universal Studios Singapore',category:'Theme park',description:'Movie-themed rides and shows on Sentosa Island.',adultPrice:83,childPrice:62,currency:'SGD',aedAdult:239,aedChild:179,lastChecked:checked,pricingNote:'One-day ticket estimate; date-based pricing varies.',latitude:1.254,longitude:103.8238,indoor:true,outdoor:true,familyFriendly:true,duration:'Full day',bestTime:'Weekday opening time',accessibility:'Accessible park; ride transfer requirements vary',address:'8 Sentosa Gateway, Singapore',saved:false}),
 a({id:'sg-jewel',country:'Singapore',city:'Singapore',name:'Jewel Changi Airport',category:'Landmark',description:'Indoor rainforest, Rain Vortex, dining and Canopy Park.',adultPrice:0,childPrice:0,currency:'SGD',aedAdult:0,aedChild:0,freeEntry:true,lastChecked:checked,pricingNote:'Rain Vortex and mall entry are free; Canopy Park attractions cost extra.',latitude:1.3602,longitude:103.9897,indoor:true,outdoor:false,familyFriendly:true,duration:'2–4 hours',bestTime:'Arrival or departure day',accessibility:'Fully accessible',address:'78 Airport Boulevard, Singapore',saved:false}),
 a({id:'sg-national-gallery',country:'Singapore',city:'Singapore',name:'National Gallery Singapore',category:'Museum',description:'Southeast Asian art in restored civic buildings.',adultPrice:20,childPrice:0,currency:'SGD',aedAdult:58,aedChild:0,lastChecked:checked,pricingNote:'General admission estimate; some exhibitions extra.',latitude:1.2906,longitude:103.851,indoor:true,outdoor:false,familyFriendly:true,duration:'2–3 hours',bestTime:'Afternoon',accessibility:'Wheelchair accessible',address:'1 St Andrew’s Road, Singapore',saved:false}),
 a({id:'sg-river-cruise',country:'Singapore',city:'Singapore',name:'Singapore River Cruise',category:'City tour',description:'Bumboat cruise past Clarke Quay, Boat Quay and Marina Bay.',adultPrice:28,childPrice:18,currency:'SGD',aedAdult:81,aedChild:52,lastChecked:checked,pricingNote:'Standard sightseeing cruise estimate.',latitude:1.2897,longitude:103.8467,indoor:false,outdoor:true,familyFriendly:true,duration:'40–60 minutes',bestTime:'Evening',accessibility:'Step-free access depends on jetty and tide',address:'Clarke Quay Jetty, Singapore',saved:false}),
 a({id:'sg-bird-paradise',country:'Singapore',city:'Singapore',name:'Bird Paradise',category:'Wildlife',description:'Large walk-through aviaries at Mandai Wildlife Reserve.',adultPrice:49,childPrice:34,currency:'SGD',aedAdult:141,aedChild:98,lastChecked:checked,pricingNote:'Online admission estimate.',latitude:1.4116,longitude:103.7879,indoor:false,outdoor:true,familyFriendly:true,duration:'4–5 hours',bestTime:'Morning',accessibility:'Wheelchair and stroller friendly',address:'20 Mandai Lake Road, Singapore',saved:false}),

// Indonesia — Jakarta only
 a({id:'id-monas',country:'Indonesia',city:'Jakarta',name:'National Monument (Monas)',category:'Landmark',description:'Jakarta’s national monument with museum and observation deck.',adultPrice:24000,childPrice:13000,currency:'IDR',aedAdult:5,aedChild:3,lastChecked:checked,pricingNote:'Estimate for monument and top access; card payment may be required.',latitude:-6.1754,longitude:106.8272,indoor:true,outdoor:true,familyFriendly:true,duration:'2–3 hours',bestTime:'Morning',accessibility:'Lift access; queues and plaza walking',address:'Merdeka Square, Central Jakarta',saved:false}),
 a({id:'id-kota-tua',country:'Indonesia',city:'Jakarta',name:'Kota Tua Jakarta',category:'Culture',description:'Historic old-town square with colonial buildings, cafés and museums.',adultPrice:0,childPrice:0,currency:'IDR',aedAdult:0,aedChild:0,freeEntry:true,lastChecked:checked,pricingNote:'Square is free; individual museums charge small fees.',latitude:-6.1352,longitude:106.8133,indoor:true,outdoor:true,familyFriendly:true,duration:'3–4 hours',bestTime:'Late afternoon',accessibility:'Mostly flat square; museum access varies',address:'Taman Fatahillah, West Jakarta',saved:false}),
 a({id:'id-fatahillah',country:'Indonesia',city:'Jakarta',name:'Jakarta History Museum',category:'Museum',description:'City history museum inside the former colonial city hall.',adultPrice:10000,childPrice:5000,currency:'IDR',aedAdult:2,aedChild:1,lastChecked:checked,pricingNote:'Local museum fare estimate.',latitude:-6.1351,longitude:106.813,indoor:true,outdoor:false,familyFriendly:true,duration:'1–2 hours',bestTime:'Morning',accessibility:'Historic building; some areas have stairs',address:'Jalan Taman Fatahillah No.1, West Jakarta',saved:false}),
 a({id:'id-istiqlal',country:'Indonesia',city:'Jakarta',name:'Istiqlal Mosque',category:'Culture',description:'Southeast Asia’s largest mosque, opposite Jakarta Cathedral.',adultPrice:0,childPrice:0,currency:'IDR',aedAdult:0,aedChild:0,freeEntry:true,lastChecked:checked,pricingNote:'Free entry; modest clothing and visitor procedures apply.',latitude:-6.1702,longitude:106.8314,indoor:true,outdoor:true,familyFriendly:true,duration:'1–1.5 hours',bestTime:'Outside prayer peak times',accessibility:'Accessible entrances and lifts',address:'Jalan Taman Wijaya Kusuma, Central Jakarta',saved:false}),
 a({id:'id-cathedral',country:'Indonesia',city:'Jakarta',name:'Jakarta Cathedral',category:'Culture',description:'Neo-Gothic cathedral and museum across from Istiqlal Mosque.',adultPrice:0,childPrice:0,currency:'IDR',aedAdult:0,aedChild:0,freeEntry:true,lastChecked:checked,pricingNote:'Free entry; donations optional.',latitude:-6.1692,longitude:106.8331,indoor:true,outdoor:false,familyFriendly:true,duration:'45–75 minutes',bestTime:'Morning',accessibility:'Mostly accessible',address:'Jalan Katedral No.7B, Central Jakarta',saved:false}),
 a({id:'id-ancol',country:'Indonesia',city:'Jakarta',name:'Ancol Dreamland',category:'Family',description:'Waterfront recreation complex with beaches, parks and attractions.',adultPrice:35000,childPrice:35000,currency:'IDR',aedAdult:8,aedChild:8,lastChecked:checked,pricingNote:'Ancol gate admission only; individual attractions cost extra.',latitude:-6.1256,longitude:106.8364,indoor:false,outdoor:true,familyFriendly:true,duration:'Half or full day',bestTime:'Morning or sunset',accessibility:'Large site; accessible transport recommended',address:'Jalan Lodan Timur No.7, North Jakarta',saved:false}),
 a({id:'id-dufan',country:'Indonesia',city:'Jakarta',name:'Dunia Fantasi (Dufan)',category:'Theme park',description:'Jakarta amusement park with thrill rides and family areas.',adultPrice:400000,childPrice:400000,currency:'IDR',aedAdult:89,aedChild:89,lastChecked:checked,pricingNote:'Weekday online estimate; weekend and fast-track prices vary.',latitude:-6.1253,longitude:106.8335,indoor:true,outdoor:true,familyFriendly:true,duration:'Full day',bestTime:'Opening time',accessibility:'Accessible paths; ride restrictions apply',address:'Ancol Dreamland, North Jakarta',saved:false}),
 a({id:'id-seaworld',country:'Indonesia',city:'Jakarta',name:'Sea World Ancol',category:'Family',description:'Indoor aquarium with tunnels, marine exhibits and feeding shows.',adultPrice:150000,childPrice:150000,currency:'IDR',aedAdult:33,aedChild:33,lastChecked:checked,pricingNote:'Weekday estimate; Ancol gate admission may be separate.',latitude:-6.1266,longitude:106.8428,indoor:true,outdoor:false,familyFriendly:true,duration:'2–3 hours',bestTime:'Midday',accessibility:'Wheelchair friendly',address:'Ancol Dreamland, North Jakarta',saved:false}),
 a({id:'id-ragunan',country:'Indonesia',city:'Jakarta',name:'Ragunan Zoo',category:'Wildlife',description:'Large, leafy zoo with Indonesian wildlife and primate centre.',adultPrice:4000,childPrice:3000,currency:'IDR',aedAdult:1,aedChild:1,lastChecked:checked,pricingNote:'Low local entry fare; transport inside and special exhibits extra.',latitude:-6.3114,longitude:106.8206,indoor:false,outdoor:true,familyFriendly:true,duration:'4–6 hours',bestTime:'Early morning',accessibility:'Large distances; some accessible paths',address:'Jalan Harsono RM No.1, South Jakarta',saved:false}),
 a({id:'id-tmii',country:'Indonesia',city:'Jakarta',name:'Taman Mini Indonesia Indah',category:'Culture',description:'Cultural park showcasing Indonesia’s provinces, architecture and museums.',adultPrice:35000,childPrice:35000,currency:'IDR',aedAdult:8,aedChild:8,lastChecked:checked,pricingNote:'Gate admission estimate; museums and rides may cost extra.',latitude:-6.3024,longitude:106.8952,indoor:true,outdoor:true,familyFriendly:true,duration:'Half or full day',bestTime:'Morning',accessibility:'Large site; shuttle or bicycle helpful',address:'Ceger, East Jakarta',saved:false}),
 a({id:'id-museum-nasional',country:'Indonesia',city:'Jakarta',name:'Museum Nasional Indonesia',category:'Museum',description:'Major archaeology, ethnography and history collection near Monas.',adultPrice:50000,childPrice:25000,currency:'IDR',aedAdult:11,aedChild:6,lastChecked:checked,pricingNote:'Visitor estimate; temporary exhibitions may differ.',latitude:-6.1764,longitude:106.8228,indoor:true,outdoor:false,familyFriendly:true,duration:'2–3 hours',bestTime:'Afternoon',accessibility:'Wheelchair accessible main galleries',address:'Jalan Medan Merdeka Barat No.12, Central Jakarta',saved:false}),
 a({id:'id-mac-an',country:'Indonesia',city:'Jakarta',name:'Museum MACAN',category:'Museum',description:'Modern and contemporary art museum with rotating exhibitions.',adultPrice:100000,childPrice:80000,currency:'IDR',aedAdult:22,aedChild:18,lastChecked:checked,pricingNote:'Timed ticket estimate; exhibitions change.',latitude:-6.1901,longitude:106.7674,indoor:true,outdoor:false,familyFriendly:true,duration:'2 hours',bestTime:'Weekday afternoon',accessibility:'Wheelchair accessible',address:'AKR Tower, Kebon Jeruk, West Jakarta',saved:false}),
 a({id:'id-gbk',country:'Indonesia',city:'Jakarta',name:'Gelora Bung Karno & Senayan',category:'City walk',description:'Stadium district with parks, malls, cafés and evening activity.',adultPrice:0,childPrice:0,currency:'IDR',aedAdult:0,aedChild:0,freeEntry:true,lastChecked:checked,pricingNote:'Public outdoor areas are free; events and venues charge separately.',latitude:-6.2186,longitude:106.8025,indoor:false,outdoor:true,familyFriendly:true,duration:'2–3 hours',bestTime:'Late afternoon or evening',accessibility:'Wide paved paths',address:'Gelora, Central Jakarta',saved:false}),
];
