import type { CountryName } from './db';

export type FoodPlace = {
  id: string;
  country: CountryName;
  city: string;
  name: string;
  kind: 'Restaurant' | 'Convenience';
  cuisine: string;
  reviewFavourite: string;
  halalAssurance: string;
  address: string;
  latitude: number;
  longitude: number;
  sourceUrl: string;
  reviewUrl: string;
};

// Curated halal-only shortlist for the three trip cities. Certification and menus
// can change, so every card links to a current verification/review source.
export const foodPlaces: FoodPlace[] = [
  { id:'my-village-park', country:'Malaysia', city:'Kuala Lumpur', name:'Village Park Restaurant', kind:'Restaurant', cuisine:'Malay · Nasi lemak', reviewFavourite:'Nasi lemak with ayam goreng berempah', halalAssurance:'Muslim-owned; widely listed as halal. Re-check signage before ordering.', address:'5 Jalan SS 21/37, Damansara Utama, Petaling Jaya, Selangor', latitude:3.1348, longitude:101.6232, sourceUrl:'https://www.havehalalwilltravel.com/halal-restaurants/malaysia/kuala-lumpur', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Village+Park+Restaurant+Damansara+Utama' },
  { id:'my-pelita', country:'Malaysia', city:'Kuala Lumpur', name:'Nasi Kandar Pelita', kind:'Restaurant', cuisine:'Malaysian Indian · Nasi kandar', reviewFavourite:'Mixed curry nasi kandar with fried chicken', halalAssurance:'Halal restaurant chain; verify the displayed JAKIM certificate at the outlet.', address:'149 Jalan Ampang, Kuala Lumpur', latitude:3.1590, longitude:101.7148, sourceUrl:'https://www.trustedmalaysia.com/best-halal-restaurants-kuala-lumpur/', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Nasi+Kandar+Pelita+Jalan+Ampang' },
  { id:'my-dolly', country:'Malaysia', city:'Kuala Lumpur', name:'Dolly Dim Sum', kind:'Restaurant', cuisine:'Halal Chinese · Dim sum', reviewFavourite:'Siew mai and salted egg custard bun', halalAssurance:'Halal-certified menu; confirm the current certificate at the chosen branch.', address:'Avenue K, 156 Jalan Ampang, Kuala Lumpur', latitude:3.1599, longitude:101.7141, sourceUrl:'https://www.havehalalwilltravel.com/halal-restaurants/malaysia/kuala-lumpur', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Dolly+Dim+Sum+Avenue+K' },
  { id:'my-damascus', country:'Malaysia', city:'Kuala Lumpur', name:'Damascus Bukit Bintang', kind:'Restaurant', cuisine:'Syrian · Middle Eastern', reviewFavourite:'Chicken shawarma and mixed grill', halalAssurance:'Muslim-owned halal restaurant; confirm at the outlet.', address:'Bukit Bintang, Kuala Lumpur', latitude:3.1474, longitude:101.7119, sourceUrl:'https://www.trustedmalaysia.com/best-halal-restaurants-kuala-lumpur/', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Damascus+Bukit+Bintang' },
  { id:'my-mynews', country:'Malaysia', city:'Kuala Lumpur', name:'myNEWS convenience store', kind:'Convenience', cuisine:'Packaged snacks · Drinks · Ready meals', reviewFavourite:'Maru Kafe onigiri and halal-labelled hot snacks', halalAssurance:'Choose only products carrying a valid JAKIM halal logo; the whole shop is not represented as halal-certified.', address:'Suria KLCC, Kuala Lumpur City Centre', latitude:3.1577, longitude:101.7121, sourceUrl:'https://www.halal.gov.my/', reviewUrl:'https://www.google.com/maps/search/?api=1&query=myNEWS+Suria+KLCC' },

  { id:'sg-zamzam', country:'Singapore', city:'Singapore', name:'Singapore Zam Zam', kind:'Restaurant', cuisine:'Indian Muslim · Murtabak · Biryani', reviewFavourite:'Mutton murtabak', halalAssurance:'MUIS halal-certified listing; verify the certificate expiry at the premises.', address:'697-699 North Bridge Road, Singapore', latitude:1.3022, longitude:103.8587, sourceUrl:'https://www.foodadvisor.com.sg/eatery/muis-halal-certified-restaurant/', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Singapore+Zam+Zam' },
  { id:'sg-positano', country:'Singapore', city:'Singapore', name:'Positano Risto', kind:'Restaurant', cuisine:'Italian · Pizza · Pasta', reviewFavourite:'Truffle mushroom pizza and squid-ink pasta', halalAssurance:'MUIS halal-certified; check the current certificate at the restaurant.', address:'66 Bussorah Street, Singapore', latitude:1.3016, longitude:103.8597, sourceUrl:'https://www.sassymamasg.com/eat-halal-restaurants-cafes/', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Positano+Risto+Singapore' },
  { id:'sg-malayan-council', country:'Singapore', city:'Singapore', name:'The Malayan Council', kind:'Restaurant', cuisine:'Malay-Western fusion', reviewFavourite:'Roti kirai beef ribs and ondeh-ondeh cake', halalAssurance:'Muslim-owned halal establishment; verify current status at the outlet.', address:'71 Bussorah Street, Singapore', latitude:1.3020, longitude:103.8594, sourceUrl:'https://www.sassymamasg.com/eat-halal-restaurants-cafes/', reviewUrl:'https://www.google.com/maps/search/?api=1&query=The+Malayan+Council+Bussorah' },
  { id:'sg-hjh-maimunah', country:'Singapore', city:'Singapore', name:'Hjh Maimunah Restaurant', kind:'Restaurant', cuisine:'Malay · Indonesian · Nasi padang', reviewFavourite:'Beef rendang and tahu telur', halalAssurance:'MUIS halal-certified; verify the displayed certificate.', address:'11 Jalan Pisang, Singapore', latitude:1.3026, longitude:103.8588, sourceUrl:'https://www.visitsingapore.com/things-to-do/dining/halal/', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Hjh+Maimunah+Jalan+Pisang' },
  { id:'sg-fairprice', country:'Singapore', city:'Singapore', name:'FairPrice Finest / Xpress', kind:'Convenience', cuisine:'Groceries · Packaged food · Ready meals', reviewFavourite:'Halal-labelled ready meals, snacks and drinks', halalAssurance:'Buy only items displaying the MUIS halal mark; the store itself carries mixed products.', address:'Marina One, 5 Straits View, Singapore', latitude:1.2776, longitude:103.8524, sourceUrl:'https://www.muis.gov.sg/halal', reviewUrl:'https://www.google.com/maps/search/?api=1&query=FairPrice+Finest+Marina+One' },

  { id:'id-sate-senayan', country:'Indonesia', city:'Jakarta', name:'Sate Khas Senayan', kind:'Restaurant', cuisine:'Indonesian · Satay · Javanese', reviewFavourite:'Chicken satay with peanut sauce', halalAssurance:'Halal Indonesian chain; verify the current BPJPH certificate at the branch.', address:'Grand Indonesia, Jalan M.H. Thamrin, Jakarta', latitude:-6.1952, longitude:106.8208, sourceUrl:'https://www.havehalalwilltravel.com/halal-restaurants/indonesia/jakarta', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Sate+Khas+Senayan+Grand+Indonesia' },
  { id:'id-remboelan', country:'Indonesia', city:'Jakarta', name:'Remboelan', kind:'Restaurant', cuisine:'Indonesian archipelago', reviewFavourite:'Nasi bakar and iga bakar', halalAssurance:'Halal menu; confirm the current BPJPH certification at the outlet.', address:'Plaza Senayan, Jakarta', latitude:-6.2250, longitude:106.7993, sourceUrl:'https://www.havehalalwilltravel.com/halal-restaurants/indonesia/jakarta', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Remboelan+Plaza+Senayan' },
  { id:'id-seribu-rasa', country:'Indonesia', city:'Jakarta', name:'Seribu Rasa', kind:'Restaurant', cuisine:'Indonesian · Southeast Asian', reviewFavourite:'Beef rendang and seafood curry', halalAssurance:'Halal-friendly Indonesian restaurant; ask the branch to show current certification.', address:'Jalan Haji Agus Salim No. 128, Menteng, Jakarta', latitude:-6.1877, longitude:106.8273, sourceUrl:'https://www.tripadvisor.com/Restaurants-g294229-zfz10751-Jakarta_Java.html', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Seribu+Rasa+Menteng' },
  { id:'id-halal-guys', country:'Indonesia', city:'Jakarta', name:'The Halal Guys', kind:'Restaurant', cuisine:'Middle Eastern-American · Rice platters', reviewFavourite:'Chicken and gyro combo platter with white sauce', halalAssurance:'Halal-certified brand/outlet; verify the certificate at the selected branch.', address:'Grand Indonesia, Jalan M.H. Thamrin, Jakarta', latitude:-6.1950, longitude:106.8206, sourceUrl:'https://whatsnewindonesia.com/jakarta/ultimate-guide/food-and-drink/halal-restaurants-try-jakarta', reviewUrl:'https://www.google.com/maps/search/?api=1&query=The+Halal+Guys+Grand+Indonesia' },
  { id:'id-alfamart', country:'Indonesia', city:'Jakarta', name:'Alfamart convenience store', kind:'Convenience', cuisine:'Groceries · Snacks · Drinks · Ready food', reviewFavourite:'Halal-labelled instant meals, breads and local snacks', halalAssurance:'Choose products carrying the BPJPH/MUI halal logo; stores may stock mixed categories.', address:'Jalan Kebon Kacang Raya, Tanah Abang, Jakarta', latitude:-6.1941, longitude:106.8182, sourceUrl:'https://bpjph.halal.go.id/', reviewUrl:'https://www.google.com/maps/search/?api=1&query=Alfamart+Kebon+Kacang+Jakarta' },
];
